import Head from 'next/head'
import { server } from '../config'
import { useEffect, useRef } from 'react';

function ContentForm() {
  const handleSubmit = async (event) => {
    event.preventDefault()
    const data = {
      content: event.target.content.value,
    }
    const JSONdata = JSON.stringify(data)
    const endpoint = `/api/articles`

    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSONdata,
    }

    const response = await fetch(endpoint, options)
    await response.json()
    location.reload()
  }

  const inputRef = useRef(null)

  useEffect(() => {
    if(inputRef.current) {
      inputRef.current.focus()
    }
  }, [])

  return (
    <form onSubmit={handleSubmit}>
      <div className="mb-3">
        <label htmlFor="content" className="form-label">암거나 쓰고 엔터</label>
        <input type="text" className="form-control" id="content" name="content" ref={inputRef}/>
      </div>
    </form>
  )
}


export async function getServerSideProps() {
  const res = await fetch(`${server}/api/articles`, {headers: {'Content-Type': 'application/json'}})
  const data = await res.json()
  return { props: { data } }
}


export default function Home(props) {
  
  return (
    <div>
      <Head>
        <title>Growth03 Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-4 container-sm'>

        <h1>
          그로스데이 보드
        </h1>

        <ContentForm />

        <div className='flex-column'>
          {
            props.data.map(article => 
              <div className="card mb-2 shadow-sm" key={article.created_before}>
                <div className="card-body">
                  <h5 className="card-title">{article.content}</h5>
                  <p className="card-text">{article.created_before}</p>
                </div>
              </div>
            )
          }
        </div>
      </main>
    </div>
  )
}
